/** Represents different maps that you can getTestSap
*@author Brandon Blaschke
*/
class Map {

  /**
  * Get the test map
  * @return {String} String for test map
  */
  static getTestMap() {
    let test =
      "33333333333333333333333333333333333333333333333333333333333333333333333\n" +
      "3RQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSRRRRQQQRQRQQRQQ3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQT3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQRTRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQRQQRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3QQRRRUTQRUTQQRSTQSUTQRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRUTUQRQQRUUQQRSUTQRQQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQRQSRUTQRQRQRQUUTQRQUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQTRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQRURSQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTSUTQRQQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQRQSRUTQRQRQURQTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRUQRQRTRQRRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQURSQTQRSQURQRQQRURSQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQRQQRSQRRRQQRQRQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTRUTTQSUTQRQQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQRTRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQRQQRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3QQRRRUTQRUTQQRSTQSUTQRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRUTUQRQQRUUQQRSUTQRQQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQRQSRUTQRQRQRQUUTQRQUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQTRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQRURSQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "33333333333333333333333333333333333333333333333333333333333333333333333\n";
    return test;
  }

  /**
  * Get the test map for objects
  * @return {String} String for test map
  */
  static getTestMapO() {
    let test =
      "33333333333333333333333333333333333333333333333333333333333333333333333\n" +
      "3pQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRpRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRp3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSRRRRQQQRQRQQRQQ3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQT3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQRQSRUTQRQRQRQUTpRQRUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQRTRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQRQQRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3QQRRRUTQRUTQQRSTQSUTQRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRUTUQRQQRUUQQRSUTQRQQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQRQSRUTQRQRQRQUUTQRQUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQTRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQRURSQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTSUTQRQQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQRQSRUTQRQRQURQTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRUQRQRTRQRRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQURSQTQRSQURQRQQRURSQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQRQQRSQRRRQQRQRQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTRUTTQSUTQRQQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQRTRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURSRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3RQQRQQRSQRRRQQQRQRQQRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRRRUTQRUTQRUTTQSUTQRQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQQURSQTQRSQUQRQRQQRURQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3QQRRRUTQRUTQQRSTQSUTQRQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3QQRUTUQRQQRUUQQRSUTQRQQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3QRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQRQSRUTQRQRQRQUUTQRQUQRQRQSRUTQRQRQRQUTQRQRUQRQRQSRUTQRQRQRQUTQRQRUQ3\n" +
      "3RQTQSRQRQRRRQRQUQRQTRQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTQ3\n" +
      "3RQQURSQTQRSQUQRQRQRURSQRQTQSRQRQRRRQRQUQRQRTRQRQTQSRQRQRRRQRQUQRQRTRQ3\n" +
      "3pQQRQQRSQRRRQQQRQQQRQQRQRQQQRQQRQUTQRQUTQURQTQQRQQQRQQRQUTQRQUTQURQTp3\n" +
      "33333333333333333333333333333333333333333333333333333333333333333333333\n";

      return test;
  }
}
